name: CI/CD Workflow

on:
  push:
    branches: [main, develop] # Trigger on pushes to these branches
  pull_request:
    branches: [main, develop] # Trigger on pull requests to these branches

jobs:
  build_and_test:
    runs-on: ubuntu-latest # Or other suitable runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment (Dependencies, Variables)
        run: |
          # Install dependencies (example: Node.js)
          npm install

          # Set environment variables (example)
          echo "MY_VAR=my_value" >> $GITHUB_ENV # More secure way to set env variables
          export MY_VAR=$MY_VAR # Make it available to script

          # Any other environment setup

      - name: Create temporary directory
        run: mkdir tmp_build_dir

      - name: Copy code to build directory
        run: cp -r ./* tmp_build_dir/  # Copy all files

      - name: Compile/Build application
        working-directory: ./tmp_build_dir  # Important: Change to build dir
        run: |
          # Your build commands here (e.g., make, npm run build, etc.)
          # Example: make

      - name: Run tests
        working-directory: ./tmp_build_dir
        run: |
          # Your test commands here (e.g., npm test, pytest, etc.)
          # Example: npm test

      - name: Stop application (if running)
        if: always() # Run even if previous steps fail
        run: |
          # Commands to stop your application.  Be careful!
          # Example: systemctl stop myapp || true # The || true suppresses errors if not running

      - name: Rename original directory (backup)
        if: always()
        run: |
          if [ -d "orig_app_dir" ]; then # Check if directory exists
            mv orig_app_dir orig_app_dir_backup_$(date +%s) # Timestamped backup
          fi

      - name: Rename build directory to original
        working-directory: ./
        run: mv tmp_build_dir orig_app_dir

      - name: Start application
        if: always() # Start even if tests failed (for debugging)
        run: |
          # Commands to start your application
          # Example: systemctl start myapp

      - name: Post-deployment steps (optional)
        if: github.ref == 'refs/heads/main'  # Only on pushes to main
        run: |
          # Deploy to production, send notifications, etc.
          echo "Deployment to production..."