name: Simple GitHub Actions CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checkout the code so runner can access the repo files

    - name: Setup Node.js
      uses: actions/setup-node@v3  # Install Node.js on the runner
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm install  # Install dependencies using npm

    - name: Run tests
      run: npm run test  # Use the test script defined in package.json

    - name: Build application
      run: npm run build  # Use the build script defined in package.json

    - name: Start application with PM2
      run: npx pm2 start npm --name "my-app" -- run start  # Use PM2 to start the application


